Naming/FileName:
  Exclude:
    - "fastlane/Appfile"
    - "fastlane/Matchfile"
    - "fastlane/Pluginfile"

Metrics/BlockLength:
  Exclude:
    - "fastlane/Fastfile"

Metrics/MethodLength:
  Exclude:
    - "fastlane/Fastfile"
